### ISSUE TITLE
Enhancements: Find packages

### ISSUE THREAD

**Issue by jm-observer** [MathiasPius/crates-lsp#5]
The effect is similar to the image below, I think this is the most commonly used feature of users. 
![154001](https://github.com/MathiasPius/crates-lsp/assets/50091488/8cbd5d4c-129c-43b1-b668-ad98728beb19)

**Comment by MathiasPius** [comment]
Very good idea, I actually didn't think this was possible, because we can't mirror or use the git-based repository, but I just noticed that the crates.io API does have search functionality: https://doc.rust-lang.org/cargo/reference/registry-web-api.html

I definitely think it *should* be implemented, but I don't know if I'll have the time to do it myself. If you feel like taking a shot at it, feel free :)

**Comment by jm-observer** [comment]
Okay.but i don't understand LSP, if I want to implement this feature, what aspects of LSP do I need to focus on?

**Comment by MathiasPius** [comment]
Closed by #6
